# Generated by Django 5.0.6 on 2025-06-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('msg', models.TextField()),
                ('pic', models.ImageField(upload_to='Templates')),
            ],
        ),
    ]
