# Generated by Django 5.0.6 on 2025-06-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cards_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
